### ISSUE TITLE
Block Size is limited to 256 bytes

### ISSUE THREAD

**Issue by facucc** [aws/aws-iot-core-mqtt-file-streams-embedded-c#24]
The `mqttFileDownloader_CONFIG_BLOCK_SIZE` variable limits sending blocks larger than 256 bytes.
The following lines show why it is limited to 256 bytes:
- https://github.com/aws/aws-iot-core-mqtt-file-streams-embedded-c/blob/main/source/MQTTFileDownloader.c#L534
- https://github.com/aws/aws-iot-core-mqtt-file-streams-embedded-c/blob/main/source/MQTTFileDownloader.c#L587

**Comment by kstribrnAmzn** [comment]
You're correct! The [MQTTFileDownloader.h](https://github.com/aws/aws-iot-core-mqtt-file-streams-embedded-c/blob/0875dd626221a96306d2e854a6c7bbe4318a2e95/source/include/MQTTFileDownloader.h#L59-L63) file sets this to `256`. This really should be a user configurable option as the block size is really limited to anwhere between 256 bytes to 128KB (see [doc](https://docs.aws.amazon.com/general/latest/gr/iot-core.html)).

I'm going to mark this as a bug so that we update the repository to account for this.

**Comment by kstribrnAmzn** [comment]
I've created https://github.com/aws/aws-iot-core-mqtt-file-streams-embedded-c/pull/32 to remedy this.

**Comment by kstribrnAmzn** [comment]
This fix is merged in. The block size is now configurable. Closing.
